name: Helm Chart CI

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/helm-ci.yaml'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm Chart
        run: helm lint charts/app-chart
