name: Deploy LangChain with MCP Validation
on:
  push:
    branches:
      stage
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 \
            -t <your-docker-id>/langchain-mcp-app:${{ github.sha }} .
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
      - name: Validate Kubernetes Resources with MCP
        run: |
          for file in helm/templates/*.yaml; do
            echo "Validating $file with MCP server..."
            curl -X POST ${{ secrets.MCP_SERVER_URL }}/validate \
              -H "Content-Type: application/yaml" \
              --data-binary @$file > validation_result.json
            if jq -e '.valid == false' validation_result.json; then
              echo "Validation failed for $file:"
              cat validation_result.json
              exit 1
            fi
          done
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Deploy with Helm
        env:
          KUBECONFIG: kubeconfig.yaml
        run: |
          helm dependency update ./helm
          helm upgrade --install langchain-mcp ./helm \
            -f helm/values.yaml \
            --set image.tag=${{ github.sha }} \
            --set config.openaiApiKey=${{ secrets.OPENAI_API_KEY }}